name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: npm install

      - name: Lint all
        run: npm run lint:all
        continue-on-error: true

      - name: Build Storybook
        run: npm run storybook:build:all
        continue-on-error: true

      - name: Build all
        run: npm run build:all
        continue-on-error: true

      - name: Test packages with coverage
        run: npm run test:packages:coverage
        continue-on-error: true

      - name: Test main with coverage
        run: npm run test:main:coverage
        continue-on-error: true

      - name: Enforce coverage thresholds
        run: node .github/scripts/check-coverage.js
